version: "3.8"

services:
  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: server
    volumes:
      - ./server:/var/www:delegated
